name: Rename HTML page title

on:
  workflow_dispatch:
    inputs:
      custom_title:
        description: "Enter the title for the HTML page"
        required: true
        default: "Default Title"  # Fallback title if none provided
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
 renaming-title: 
    runs-on: ubuntu-latest
    env:
      PAGE_TITLE: "${{ github.event.inputs.custom_title }}"  # Use the input title here
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Update HTML file
        run: |
          sed -i "s/<title>.*<\/title>/<title>${PAGE_TITLE}<\/title>/" docs/index.html
          
      - name: push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Auto-generate README from index.html"
          git push
